import React, { useRef } from "react";
import Footer from "@/app/components/Footer";
import "@/app/styles/style.scss";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Nav from "@/app/components/Nav";
import AuthProvider from "./context/AuthProvider";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={montserrat.className}>
          <Nav />
          <main className="main">{children}</main>
          <Footer />
        </body>
      </AuthProvider>
    </html>
  );
};

export default RootLayout;
